# Grupppo 2: Operazioni di random sampling, serializzazione, operazioni pointwise, operazioni di riduzione

In [4]:
import torch
import numpy as np
from matplotlib import pyplot as plt

### Creation and operations

In [5]:

x = torch.Tensor(2, 3)    # Create an un-initialized Tensor of size 2x3
print(x)                  # Print out the Tensor



tensor([[1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [6]:

x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values



            # [torch.FloatTensor of size 2x3]

In [7]:
eye = torch.eye(3)              # Create an identity 3x3 tensor

v1 = torch.ones(10)              # A tensor of size 10 containing all ones
print('v1')
print(v1)

v2 = torch.ones(2, 1, 2, 1)      # Size 2x1x2x1....

print('v2')
print(v2)

v3 = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.
print('v3')
print(v3)

v4 = torch.zeros(10)             # A tensor of size 10 containing all zeros
print('v4')
print(v4)




v1
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
v2
tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])
v3
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
v4
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [8]:
v = torch.arange(5)             # similar to range(5) but creating a Tensor
v = torch.arange(0, 5, step=1)  # Size 5. Similar to range(0, 5, 1)



v0 = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively

v1 = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10

v2 = torch.Tensor(2, 3)          # An un-initialized torch.FloatTensor of size 2x3

v3 = torch.Tensor([[1,2],[4,5]]) # A Tensor initialized with a specific array

v4 = torch.LongTensor([1,2,3])   # A Tensor of type Long



c = torch.ByteTensor([0, 1, 1, 0]) #bytetensor



Important to remember that the type of a tensor is very important because they have different attributes and so  you cannot make operation among them straightforwardly

In [9]:
torch.is_tensor(c)

True

in Place operations end with “_” is in place operations:

In [10]:
x.add_(y)        # Same as x = x + y

tensor([[ 2.2251e-01, -8.5899e+09, -6.0648e+02],
        [ 3.1349e-01,         nan,         nan]])

In [11]:
v = torch.ones(3, 3)
v[1].fill_(2)
v[2].fill_(3)

#will generate
# 1  1  1
# 2  2  2
# 3  3  3

print(v)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


Reshape Tensors

In [12]:
### Tensor resizing
x = torch.randn(2, 3)            # Size 2x3
y = x.view(6)                    # Resize x to size 6
z = x.view(-1, 2)                # Size 3x2

v = torch.ones(9)
v = v.view(3, 3)                 #Size 3,3


print(x.size())      # tensor.size like np.shape 
print(y.size())
print(z.size())
print(v.size())

torch.Size([2, 3])
torch.Size([6])
torch.Size([3, 2])
torch.Size([3, 3])


In [13]:
v = v.view(-1,3) # -1 matches the other dimension, it gives you error if is not possible to match like v.view(-1,2)
                # indeed, v has 9 elements and it can just be reshaped in 3,3 
print(v)    

v2 = torch.ones(16)
v2.view(2,2,-1)         # reshape a 1d tensor to a 3d tensor of 2 element per plane (2planes) where 
                        #you need to have (the -1 dim) 4 elements to match the size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
#this two are equal

x.size()
torch.numel(x)        


6

Basic Operations among tensors, the logic

In [15]:

# Operations
x = torch.arange(9).float()

y = torch.rand(9)

z1 = x + y
z2 = torch.add(x, y)             # Same as above

print(z2)            

tensor([0.7576, 1.1091, 2.3059, 3.1591, 4.8885, 5.6264, 6.6783, 7.7181, 8.3030])


In [16]:
r1 = torch.Tensor(2, 3) #random inizialization

r2 = torch.add(x, y, out=r1)   # defines r2 and also rewrite r1

r3 = torch.add(x, y)


In [17]:
print(r2)
print(r3)
print(r1)

tensor([0.7576, 1.1091, 2.3059, 3.1591, 4.8885, 5.6264, 6.6783, 7.7181, 8.3030])
tensor([0.7576, 1.1091, 2.3059, 3.1591, 4.8885, 5.6264, 6.6783, 7.7181, 8.3030])
tensor([0.7576, 1.1091, 2.3059, 3.1591, 4.8885, 5.6264, 6.6783, 7.7181, 8.3030])


Numpy connection 

In [18]:
x= x.view(3,-1)

print(x[:, 1])                      # Can use numpy type indexing
print(x[:,0])

x[:, 0] = 0                      # For assignment
print(x[:,0])



# like in numpy
x1 =np.zeros(4)
x2=x1.reshape(2,2)
x2[:,1]=0

#reshape works also for tensor and is similar to view x.reshape(3,3)


tensor([1., 4., 7.])
tensor([0., 3., 6.])
tensor([0., 0., 0.])


## Random Tensors

In [19]:
torch.manual_seed(1)

In [20]:
x = torch.randn(5, 3).type(torch.FloatTensor)

In [21]:
# 2x2: A uniform distributed random matrix with range [0, 1]
r = torch.Tensor(2, 2).uniform_(0, 1)

# bernoulli
r = torch.bernoulli(r)   # Size: 2x2. Bernoulli with probability p stored in elements of r

# Multinomial
w = torch.Tensor([0, 4, 8, 2]) # Create a tensor of weights
r = torch.multinomial(w, 4, replacement=True) # Size 4: 3, 2, 1, 2

print(r)

# Normal distribution
# From 10 means and SD
r = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

print(r)

tensor([3, 3, 3, 3])
tensor([ 1.2673,  2.2930,  2.6167,  4.9653,  6.5171,  6.2054,  6.6048,  7.7276,
         9.1085, 10.0110])


In [22]:
#one single element tensor as to be specified with or mean or std a Float tensor of single element 
r0 =torch.normal(mean=2, std=torch.tensor([2]).float()) 

## Concatenation opearitions

In [23]:
# Concatenation

x= torch.zeros(3,3)
x[:,1] =1
x[0].fill_(-2)
x[2].fill_(3)


v= torch.ones(3,3)
v[1,:2].fill_(-2)

r0=torch.cat((x, x, x),0)          # Concatenate in the 0 dimension ~ one over the other
r0b= torch.cat((x, x, x),1)        # Concatenate in the 1 dimension ~one next to the other

# Stack IS NOT cat because it stack with a new dimension the new tensor, do not merge the tensors like cat
r1 = torch.stack((v, v))
r1b= torch.cat((v,v),0)        

print(r0)
print(r0b)
print(r1)
print(r1b)

tensor([[-2., -2., -2.],
        [ 0.,  1.,  0.],
        [ 3.,  3.,  3.],
        [-2., -2., -2.],
        [ 0.,  1.,  0.],
        [ 3.,  3.,  3.],
        [-2., -2., -2.],
        [ 0.,  1.,  0.],
        [ 3.,  3.,  3.]])
tensor([[-2., -2., -2., -2., -2., -2., -2., -2., -2.],
        [ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
        [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])
tensor([[[ 1.,  1.,  1.],
         [-2., -2.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [-2., -2.,  1.],
         [ 1.,  1.,  1.]]])
tensor([[ 1.,  1.,  1.],
        [-2., -2.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [-2., -2.,  1.],
        [ 1.,  1.,  1.]])


In [24]:
# Gather element
# torch.gather(input, dim, index, out=None)
# out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
# out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
# out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2

# 0  1
# 4  3
# 8  7

v = torch.arange(9)
v = v.view(3, 3)

r = torch.gather(v, 1, torch.LongTensor([[0,1],[1,0],[2,1]]))


# gather gives you a new tensor with the element of the input tensor at the index of the index_tensor , 
#taken in the direction of dim --> 1 normal direction ,-1 in the backward direction
# I see the -1 dimension as if you look the  tensor from behind, so for nxn tensor 
#is like looking at the tensor on te other direction

In [25]:
print(v.size())
print(r.size())
print(v)
print(r)

torch.Size([3, 3])
torch.Size([3, 2])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [4, 3],
        [8, 7]])


Split and chunk

In [26]:
# Split an array into 3 chunks
# (
# 0  1  2
# [torch.FloatTensor of size 1x3]
# ,
# 3  4  5
# [torch.FloatTensor of size 1x3]
# ,
# 6  7  8
# [torch.FloatTensor of size 1x3]
# )
r0 = torch.chunk(v, 3)  #basically take the tensor and creates three 
                        #tensors from it adjusting the dimension to be the same

# Split an array into chunks of at most size 2
# (
# 0  1  2
# 3  4  5
# [torch.FloatTensor of size 2x3]
# ,
# 6  7  8
# [torch.FloatTensor of size 1x3]
# )

r0b = torch.split(v, 1)  #at most size 1 it means torch.chunk(v, 3)

r1 = torch.split(v, 2)   # at most size 2 : one of 2 one of 1 dim ... it means torch.chunk(v, 2)
r2 = torch.split(v,3)   # at most size 3 one of 3 one of 0 <-check it out this zero! it means torch.chunk(v,1)

In [27]:



print(r0)
print(r0b)
print(r1)
print(r2)

(tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]))
(tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]))
(tensor([[0, 1, 2],
        [3, 4, 5]]), tensor([[6, 7, 8]]))
(tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),)


summarizing:

torch.chunk(v,n) = torch.split(v, maxDimension-n)

In [28]:
# Index select
v = torch.arange(9)
v = v.view(3, 3)
# 0 2
# 3 5
# 6 8
indices = torch.LongTensor([0, 2])
ri = torch.index_select(v, 1, indices) # Select element 0 and 2 for each dimension 1.




# Masked select
# 0  0  0
# 1  1  1
# 1  1  1


mask = v.ge(3)  #<- put zero in the element where you are smaller than 3 and 1 if you are equal or biigger
                # can be used also for comparing tensors
m2= torch.ge(torch.tensor([2,5]), torch.tensor([2,2]))

# Size 6: 3 4 5 6 7 8
rm = torch.masked_select(v, mask)



In [29]:
print(mask)
print(m2)
print(ri)
print(rm)

tensor([[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)
tensor([1, 1], dtype=torch.uint8)
tensor([[0, 2],
        [3, 5],
        [6, 8]])
tensor([3, 4, 5, 6, 7, 8])


In [30]:
t = torch.ones(2,1,2,1) # Size 2x1x2x1
r0 = torch.squeeze(t)     # Size 2x2
r1 = torch.squeeze(t, 1)  # Squeeze dimension 1: Size 2x2x1

# Un-squeeze a dimension
x = torch.Tensor([1, 2, 3])
r2 = torch.unsqueeze(x, 0)       # Size: 1x3
r3 = torch.unsqueeze(x, 1)       # Size: 3x1
r4 = torch.unsqueeze(x, -1)       # Size: 3x1

In [31]:
print(r0)
print(r1)
print(r2)
print(r3)
print(r4)

tensor([[1., 1.],
        [1., 1.]])
tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])
tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])
tensor([[1.],
        [2.],
        [3.]])


In [32]:
# Non-zero
# [torch.LongTensor of size 8x2]
# [i, j] index for non-zero elements
#    0     1
#    0     2
#    1     0
#    1     1
#    1     2
#    2     0
#    2     1
#    2     2
r = torch.nonzero(v)
print(r)

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])


In [33]:
# Flatten a TensorFlow and return elements with given indexes
# Size 3: 0, 4, 2
v= torch.arange(9)
r = torch.take(v, torch.LongTensor([0, 4, 3]))
print(r)


v=(10*torch.rand(3,3)).int()
r1 = torch.take(v, torch.LongTensor([0, 4, 3]))
print(v)
print(r1)


tensor([0, 4, 3])
tensor([[1, 1, 7],
        [3, 7, 5],
        [6, 6, 6]], dtype=torch.int32)
tensor([1, 7, 3], dtype=torch.int32)


In [34]:
# Transpose dim 0 and 1
v=torch.arange(9).view(3,3)
r1 = torch.transpose(v,0,1)
print(r1)

v=torch.arange(27)
v=v.reshape(3,3,-1)
print(v.size())

r2 = torch.transpose(v,1,0)
print(r2)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
torch.Size([3, 3, 3])
tensor([[[ 0,  1,  2],
         [ 9, 10, 11],
         [18, 19, 20]],

        [[ 3,  4,  5],
         [12, 13, 14],
         [21, 22, 23]],

        [[ 6,  7,  8],
         [15, 16, 17],
         [24, 25, 26]]])


### Pointwise operations

In [35]:
v = torch.arange(9)
v = v.view(3, 3)
x = torch.randn(5, 3).type(torch.FloatTensor)
y = torch.randn(5, 3).type(torch.FloatTensor)
### Math operations
f= torch.FloatTensor([-1, -2, 3])
r = torch.abs(f)      # 1 2 3

# Add x, y and scalar 10 to all elements
r = torch.add(x, 10)
r = torch.add(x, 10, y)

# Clamp the value of a Tensor
r = torch.clamp(v, min=-0.5, max=0.5)



# Element-wise divide
#r = torch.div(2*v, v) ##MY KERNEL DIES

# Element-wise multiple
r = torch.mul(v, v)

### Reduction operations

In [42]:
### Reduction operations

# Accumulate sum
#  0   1   2
#  3   5   7
#  9  12  15

v=v.float()

r = torch.cumsum(v, dim=0)
print(r)

# L-P norm

r = torch.dist(v, v+3, p=2)  # L-2 norm: ((3^2)*9)^(1/2) = 9.0

# Mean
# 1 4 7
r = torch.mean(v, 1)         # Size 3: Mean in dim 1

r = torch.mean(v, 1, True)   # Size 3x1 since keep dimension = True

# Sum
# 3 12 21
r = torch.sum(v, 1)          # Sum over dim 1

# 36
r = torch.sum(v)

tensor([[ 0.,  1.,  2.],
        [ 3.,  5.,  7.],
        [ 9., 12., 15.]])


### Comparison Operations

In [50]:
# Size 3x3: Element-wise comparison
v=4*torch.randn(9).view(3,-1)
print(v)
r = torch.eq(v, v)

# Max element with corresponding index
r1 = torch.max(v, 1)    # the ouptut are two tensors, one of the max along the dim 1 
                        #and one of the indexes for the max location

print(r)
print(r1)


tensor([[-3.7931,  0.3771,  2.5407],
        [-2.4214, -1.1351,  4.2099],
        [ 1.1458,  5.9484,  5.5220]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)
(tensor([2.5407, 4.2099, 5.9484]), tensor([2, 2, 1]))
